/**
 * Tools behind the work on the Projects page, shown as the Tools & Engines cloud.
 *
 * Unlike lib/skills.js this list is deliberately concrete: only things with a version
 * number and a download page, each pointing at the projects it actually shipped in.
 * `usedIn` ids must exist in lib/home-details.js.
 */

export const projectTools = [
  {
    id: "react",
    label: "React",
    group: "Web & App",
    icon: { slug: "react" },
    tldr: "Component-based UI library behind the interfaces on every web build here.",
    usedIn: [
      { label: "oliverms.com", detailId: "project-portfolio" },
      { label: "Nebula ID", detailId: "project-nebula-id" },
      { label: "Nebula AI", detailId: "project-nebula-ai" },
      { label: "Nebula Life", detailId: "project-nebula-life" },
      { label: "Nebula Nook", detailId: "project-nook" },
      { label: "Brim AERO", detailId: "project-brim-aero" },
      { label: "LossnFound", detailId: "project-lossnfound" },
    ],
  },
  {
    id: "nextjs",
    label: "Next.js",
    group: "Web & App",
    icon: { slug: "nextdotjs" },
    tldr: "React framework handling routing, server rendering, and API routes in one place.",
    usedIn: [
      { label: "oliverms.com", detailId: "project-portfolio" },
      { label: "Nebula ID", detailId: "project-nebula-id" },
      { label: "Cooked", detailId: "project-cooked" },
      { label: "BudgetX", detailId: "project-budgetx" },
      { label: "Brim AERO", detailId: "project-brim-aero" },
      { label: "LossnFound", detailId: "project-lossnfound" },
    ],
  },
  {
    id: "javascript",
    label: "JavaScript",
    group: "Web & App",
    icon: { slug: "javascript" },
    tldr: "The language every browser runs, and the glue in most of what I ship on the web.",
    usedIn: [
      { label: "oliverms.com", detailId: "project-portfolio" },
      { label: "Cooked", detailId: "project-cooked" },
      { label: "Nebula Nook", detailId: "project-nook" },
      { label: "Dr. Bob", detailId: "project-dr-bob" },
      { label: "Brim AERO", detailId: "project-brim-aero" },
      { label: "LossnFound", detailId: "project-lossnfound" },
    ],
  },
  {
    id: "typescript",
    label: "TypeScript",
    group: "Web & App",
    icon: { slug: "typescript" },
    tldr: "Typed JavaScript for larger web apps, so the compiler catches the mistakes before users do.",
    usedIn: [
      { label: "BudgetX", detailId: "project-budgetx" },
      { label: "Brim AERO", detailId: "project-brim-aero" },
      { label: "LossnFound", detailId: "project-lossnfound" },
    ],
  },
  {
    id: "mongodb",
    label: "MongoDB",
    group: "Web & App",
    icon: { slug: "mongodb" },
    tldr: "Document database for product data that does not want to live in rigid tables.",
    usedIn: [{ label: "Brim AERO", detailId: "project-brim-aero" }],
  },
  {
    id: "postgresql",
    label: "PostgreSQL",
    group: "Web & App",
    icon: { slug: "postgresql" },
    tldr: "Relational database behind apps that need real schemas, joins, and role-safe queries.",
    usedIn: [{ label: "LossnFound", detailId: "project-lossnfound" }],
  },
  {
    id: "drizzle",
    label: "Drizzle ORM",
    group: "Web & App",
    icon: { slug: "drizzle" },
    tldr: "Type-safe SQL toolkit that keeps the schema and queries close to the TypeScript source.",
    usedIn: [{ label: "LossnFound", detailId: "project-lossnfound" }],
  },
  {
    id: "tauri",
    label: "Tauri",
    group: "Web & App",
    icon: { slug: "tauri" },
    tldr: "Desktop shell that pairs a web frontend with a Rust core, for a fraction of Electron's weight.",
    usedIn: [{ label: "Nebula Nook", detailId: "project-nook" }],
  },
  {
    id: "rust",
    label: "Rust",
    group: "Web & App",
    icon: { slug: "rust" },
    tldr: "Systems language I use for the native side of desktop builds, where memory safety matters.",
    usedIn: [{ label: "Nebula Nook", detailId: "project-nook" }],
  },
  {
    id: "firebase",
    label: "Firebase",
    group: "Web & App",
    icon: { slug: "firebase" },
    tldr: "Hosted auth, database, and deploys, so a hackathon build can go live the same day.",
    usedIn: [{ label: "Cooked", detailId: "project-cooked" }],
  },
  {
    id: "threejs",
    label: "Three.js",
    group: "Web & App",
    icon: { slug: "threedotjs" },
    tldr: "WebGL toolkit for 3D scenes in the browser when a demo needs more than flat UI.",
    usedIn: [{ label: "LossnFound", detailId: "project-lossnfound" }],
  },
  {
    id: "python",
    label: "Python",
    group: "AI",
    icon: { slug: "python" },
    tldr: "My default for backend services and anything that touches models or data.",
    usedIn: [
      { label: "Nebula AI", detailId: "project-nebula-ai" },
      { label: "Dr. Bob", detailId: "project-dr-bob" },
    ],
  },
  {
    id: "gemini",
    label: "Gemini API",
    group: "AI",
    icon: { slug: "googlegemini" },
    tldr: "Google's model API, wired in for generation, summarising, and judgement calls in-app.",
    usedIn: [
      { label: "Cooked", detailId: "project-cooked" },
      { label: "Dr. Bob", detailId: "project-dr-bob" },
      { label: "BudgetX", detailId: "project-budgetx" },
      { label: "Brim AERO", detailId: "project-brim-aero" },
      { label: "LossnFound", detailId: "project-lossnfound" },
      { label: "HackDécouverte, Gemini API Award", detailId: "award-hackdecouverte" },
    ],
  },
  {
    id: "twinmotion",
    label: "Twinmotion",
    group: "3D & Real-time",
    icon: { slug: "twinmotion" },
    tldr: "Architectural visualisation tool that turns building models into photoreal, walkable scenes.",
    usedIn: [
      { label: "SAJO Miami VR simulation", detailId: "project-sajo-miami-vr" },
      { label: "SAJO Montreal VR simulation", detailId: "project-sajo-montreal-vr" },
      { label: "Maeve Catalog", detailId: "project-maeve-catalog" },
      { label: "LAB_01", detailId: "achievement-lab-01-dev-team-2024" },
    ],
  },
  {
    id: "unreal",
    label: "Unreal Engine",
    group: "3D & Real-time",
    icon: { slug: "unrealengine" },
    tldr: "Real-time engine doing the lighting and rendering heavy lifting on the 3D work.",
    usedIn: [
      { label: "SAJO Miami VR simulation", detailId: "project-sajo-miami-vr" },
      { label: "Maeve Catalog", detailId: "project-maeve-catalog" },
      { label: "LAB_01", detailId: "achievement-lab-01-dev-team-2024" },
    ],
  },
  {
    id: "unity",
    label: "Unity 3D",
    group: "3D & Real-time",
    icon: { slug: "unity" },
    tldr: "Game engine I prototype interactive spaces in before committing to a final build.",
    usedIn: [{ label: "SAJO Miami office prototype", detailId: "project-sajo-miami-prototype" }],
  },
  {
    id: "roblox-studio",
    label: "Roblox Studio",
    group: "3D & Real-time",
    icon: { slug: "robloxstudio" },
    tldr: "Modeling, animation, and scene building for anything made to run on Roblox.",
    usedIn: [{ label: "Maeve Catalog", detailId: "project-maeve-catalog" }],
  },
];
